### PR TITLE
Pull and merge feature/lifecycle-fix into master

### LINKED ISSUE #81: Setting `UpdatePresenceWhenStopped` is ignored and Presence shows impossible times
**Describe the bug**
Under certain conditions the Rich Presence is displayed in Discord even though `UpdatePresenceWhenStopped` is turned off and nothing is currently played back. The presence shows information about the last track that was played.

**To Reproduce**
I'm not entirely certain about which conditions can cause this bug to appear. Here is one way to reproduce it (that is, how this bug happened to me today):
1. Start MusicBee and play some music (don't run Discord yet, `UpdatePresenceWhenStopped` should be disabled)
2. Do some housework or waste time in whatever way you prefer, and let the playlist run out (maybe a certain time of being afk is required)
3. Eventually return to the PC (playback has already run out) and start Discord
4. Admire the Rich Presence showing MusicBee and the last song that has been played, while still counting up the playtime (way above the track's duration)

**Expected behavior**
Nothing shown in Discord except my "About Me" text and other stuff that is usually shown when clicking on my name in the userlist.

**Screenshots**
discordbee
(In case you didn't know, that song is far shorter than 3h. 😉 )

**Environment (please complete the following information):**
 - MusicBee Version: **3.4.7805**
 - Plugin Version: **1.4.2**

**Additional context**
I think the key is to start Discord after MusicBee, while playback is halted but something had been played previously in the same MusicBee session (so that `UpdateDiscordPresence` had been called with `PlayState.Playing` at least once).

It may be worth to look into what `DiscordRpcClient` does on initialisation when no Discord client is currently running and then later, when Discord is run.

### PR DESCRIPTION
**Pull request by Svarr**
Fixes #81 (Rich Presence ghosting in Discord) by tracking the connection state to Discord in DiscordBee and preventing it from sending presence updates while Discord is not running.

### CODE REVIEW

**Comment by sll552** [comment]
Squash the commits pls

**Comment by Svarr** [comment]
How do I do that?

File: DiscordBee.cs [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
-using DiscordRPC.Logging;
-using System;
-using System.Collections.Generic;
-using System.Diagnostics;
-using System.Text;
-using System.Text.RegularExpressions;
-
 namespace MusicBeePlugin
 {
+  using System;
```
Comment (sll552) [inline DiscordBee.cs:3]: Why did you move the usings inside the namespace?

**Comment by sll552** [comment]
> How do I do that?
> 
> I could merge this branch into the fork's master and squash the commits this way...?

just do an interactive rebase and fixup/squash the commits into one

File: DiscordBee.cs (hunk 1 above)
Comment (Svarr) [reply DiscordBee.cs:3]: That's just something I accustomed myself to a long time ago because it's marginally (read: in rare cases) safer (see [this answer on SO](https://stackoverflow.com/a/151560)).

**Comment by Svarr** [comment]
That just added the commits on top of the old ones...

**Comment by sll552** [comment]
> That just added the commits on top of the old ones...

What git tool are you using? for commandline it would be something like `git rebase -i upstream/master` and then vim should open and you can select what happens to each commit (there you would do fixup or squash instead of pick).

For tortoisegit you would select rebase and in the window top right select upstream/master and tick the force checkbox, then the commits will be listed and you can pick/squash. 

Anyway I guess i can do it myself.

**Comment by Svarr** [comment]
> What git tool are you using? for commandline it would be something like `git rebase -i upstream/master` and then vim should open and you can select what happens to each commit (there you would do fixup or squash instead of pick).
> 
> For tortoisegit you would select rebase and in the window top right select upstream/master and tick the force checkbox, then the commits will be listed and you can pick/squash.
> 
> Anyway I guess i can do it myself.

I use Git Extensions and GitLab. Usually I do these things directly on GitLab but GitHub seems to lack most of the functionalities.

**Comment by sll552** [comment]
> I use Git Extensions and GitLab. Usually I do these things directly on GitLab but GitHub seems to lack most of the functionalities.

Well unfortunately these online tools mostly miss those "advanced" git usecases.

> > Anyway I guess i can do it myself.
> 
> That would be great. 😄

Done
