### PR TITLE
Fixes issue where Url queries get URLEncoded along with the layout element

### LINKED ISSUE #129: Custom Button doesn't open expected URL
**Describe the bug**
After setting up a custom button and it appearing on Discord Presence. It doesn't seem to work as expected.

**To Reproduce**
1. Set up custom button label and url (see screenshot)
2. Notice button appearing as expected
3. Click button to open url
4. Button doesn't open external browser window

**Expected behavior**
Clicking the button should open your default browser with the expected url.

**Screenshots**
image
image

**Environment:**
 - MusicBee Version: 3.4.7805 P
 - Plugin Version: v2.2.0

**Additional context**
I'm using discord for desktop and not the browser version. The browser console in Discord Canary (Ctrl+Shift+I) doesn't give any info about this either.

### PR DESCRIPTION
**Pull request by aikoofujimotoo**
Fixes #129

### CODE REVIEW

**Comment by DannyyyOnGit** [comment]
Would appreciate a v2.2.1 release, if possible.
Requires _DiscordBee.cs_ versioning to be updated.

File: DiscordBee.cs [hunk 1]
```diff
@@ -230,29 +228,18 @@ string padString(string input)
...
-          {
-            var result = _layoutHandler.Render(part, metaDataDict, _settings.Seperator);
-            if (part != result && (part != "_"))
-            {
-              return WebUtility.UrlEncode(result);
-            }
-
-            return part;
-          });
+        var uri = _layoutHandler.RenderUrl(_settings.ButtonUrl, metaDataDict, _settings.Seperator);
```
Comment (sll552) [inline DiscordBee.cs:231]: I think separators should be empty in this case because some of those characters might be part of the userdefined URL and then they would be stripped and therefore the URL would be malformed in a non expected way.

Comment (aikoofujimotoo) [reply DiscordBee.cs]: Oh yeah I forgot. Anyways, I changed it on the latest commit.
